### PR TITLE
#416 add filter for app and app version in violation, fix final, allo…

### LINKED ISSUE #416: add filter for app and app version in API violations
### Expected behavior
add filter for app and app version in API violations
allow list of types in violation controller
fix final modifier
### Step needed
add 2 filter
### Dependencies
DB columns already created

### PR DESCRIPTION
**Pull request by mrandi**
…w list of types in violation controller

fixes #416

### CODE REVIEW

**Comment by harti2006** [comment]
:+1:

File: fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/repository/impl/ViolationRepositoryImpl.java [hunk 1]
```diff
@@ -89,7 +97,15 @@ public ViolationRepositoryImpl() {
         }
 
         if (type != null) {
-            predicates.add(qViolationEntity.violationTypeEntity.id.eq(type));
+            predicates.add(qViolationEntity.violationTypeEntity.id.in(type));
+        }
+
+        if (applicationNames != null) {
```
Comment (harti2006) [inline fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/repository/impl/ViolationRepositoryImpl.java]: maybe `if (isNotEmpty(applicationNames))`

**Comment by harti2006** [comment]
:+1:
