### PR TITLE
#422 first attemt fixing date in ui

### LINKED ISSUE #422: swagger ui fix
### Expected behavior
fix date and page in swagger ui

### PR DESCRIPTION
**Pull request by mrandi**
fixes #422 

TODO:
- [x] fix datetime
- [x] fix page
- [x] remove userId

### CODE REVIEW

File: fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/model/Violation.java [hunk 1]
```diff
@@ -109,7 +109,7 @@ public void setComment(String comment) {
         this.comment = comment;
     }
 
-    @ApiModelProperty(value = "")
+    @ApiModelProperty(value = "", dataType = "DateTime", example = "2015-05-21T10:24:47.788-02:00")
```
Comment (mrandi) [inline fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/model/Violation.java]: example and datatype are not really working. I should find another solution for that

**Comment by Gregsen** [comment]
👍
