### PR TITLE
#320 catch rate limit for jobs

### LINKED ISSUE #320: Jobs: Do not log AWS rate limit exceedance as ERROR
Sporadically fullstop jobs exceed aws api request limit. In this case, a WARN log message should be logged and the job should go on with processing the next account.

Stacktrace:

```
ERROR [pool-7-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
com.amazonaws.AmazonServiceException: Request limit exceeded. (Service: AmazonEC2; Status Code: 503; Error Code: RequestLimitExceeded; Request ID: aa4ebff3-6965-42f5-8bba-a4d33e479896)
at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1239) ~[aws-java-sdk-core-1.10.35.jar!/:?]
at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:823) ~[aws-java-sdk-core-1.10.35.jar!/:?]
at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506) ~[aws-java-sdk-core-1.10.35.jar!/:?]
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318) ~[aws-java-sdk-core-1.10.35.jar!/:?]
at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:11901) ~[aws-java-sdk-ec2-1.10.35.jar!/:?]
at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:5940) ~[aws-java-sdk-ec2-1.10.35.jar!/:?]
at org.zalando.stups.fullstop.jobs.ec2.FetchEC2Job.getDescribeEC2Result(FetchEC2Job.java:221) ~[fullstop-jobs-1.2.0-SNAPSHOT.jar!/:?]
at org.zalando.stups.fullstop.jobs.ec2.FetchEC2Job.run(FetchEC2Job.java:131) ~[fullstop-jobs-1.2.0-SNAPSHOT.jar!/:?]
at sun.reflect.GeneratedMethodAccessor187.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_45-internal]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_45-internal]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_45-internal]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45-internal]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45-internal]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
```

### PR DESCRIPTION
**Pull request by mrandi**
fixes #320

### CODE REVIEW

File: fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ec2/FetchEC2Job.java [hunk 1]
```diff
@@ -128,9 +129,22 @@ public void run() {
...
+                    describeEC2Result = getDescribeEC2Result(
+                            account,
+                            region);
+                } catch (AmazonServiceException a) {
+
+                    if (a.getErrorCode().equals("RequestLimitExceeded")) {
+                        log.warn("RequestLimitExceeded for account: {}", account);
+                    }
+
+                    log.error(a.getMessage(), a);
```
Comment (harti2006) [inline fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ec2/FetchEC2Job.java]: the log.error should go into an "else" branch
